<?php
return array(
    // Settings
        'uniqueId' => '',
        'globalwidth' => 0,
        'heightwrapper' => 0, 
        'parentBlock' => '',
        'globaloff'=>false,
        'parentBlockAttributes'=>array(),

    //Advanced
        'classNamemain' => '',
        'globalwidth'=> '',
        'width' => '',
        'customWidthlayout' => '',
        'widthType' => 'default',
        'customWidthUnit' => '%',
        'customWidth' => 100,
        'customWidthTablet' => 100,
        'customWidthMobile' => 100,
        'customHeightUnit' => 'px',
        'customHeight' => 400,
        'customHeightTablet' => 400,
        'customHeightMobile' => 400,
        'position' => 'relative',
        'horizontalOrientation' => 'left',
        'horizontalOrientationOffsetUnit' => 'px',
        'horizontalOrientationOffsetRightUnit' => 'px',
        'horizontalOrientationOffset' => 0,
        'horizontalOrientationOffsetRight' => 0,
        'verticalOrientation' => 'top',
        'verticalOrientationOffsetTopUnit' => 'px',
        'verticalOrientationOffsetBottomUnit' => 'px',
        'verticalOrientationOffsetTop' => 0,
        'verticalOrientationOffsetBottom' => 0,
        'backgroundType' => 'color',
        'backgroundColor' => 'transparent',
        'backgroundImage' => null,
        'backgroundGradient' => 'linear-gradient(135deg,#0F2027 0%, #203A43 0%, #2c5364 100%)',
        'backgroundPosition' => array('x' => 0.5, 'y' => 0.5),
        'backgroundAttachment' => 'scroll',
        'backgroundRepeat' => 'no-repeat',
        'backgroundSize' => 'cover',
        'backgroundTypeHvr' => 'color',
        'backgroundColorHvr' => '',
        'backgroundImageHvr' => null,
        'backgroundGradientHvr' => 'linear-gradient(135deg,#0F2027 0%, #203A43 0%, #2c5364 100%)',
        'backgroundPositionHvr' => array('x' => 0.5, 'y' => 0.5),
        'backgroundAttachmentHvr' => 'scroll',
        'backgroundRepeatHvr' => 'no-repeat',
        'backgroundSizeHvr' => 'cover',
        'transitionAll' => 0,
        
        'advanceborder'=>array(),
        'advanceRadius'=>array(),
        'boxShadow'=> array(),
        'advancebordertype' =>  'color',
        'advancebordergradient' =>  'linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%)',
        'advancegradienttop' =>'5px',
        'advancegradientbottom' =>'5px',
        'advancegradientleft' =>'5px',
        'advancegradientright' =>'5px',
        'advanceimagetop' =>'5px',
        'advanceimagebottom' =>'5px',
        'advanceimageleft' =>'5px',
        'advanceimageright' =>'5px',
        'advanceborderimagetype' =>'none',
        'advanceborderimage' => '',
        'advancespace' =>  'space', 
        'advanceborderimagesize' => 30,    
        'advanceborderimageoutset' => 5,
        "advancegradientborderimageoutset" => 5,
);
?>
