<?php
return array(
    'uniqueId' => '',
    'heading'=> array('h1'=> true, 'h2'=>true, 'h3'=>true, 'h4'=> true, 'h5'=> true, 'h6'=> true),
    'tocTitle' => 'Table Of Contents',
    'spacing'=> array('Desktop'=>'10px','Tablet'=>'10px','Mobile'=>'10px'),
    'columns'=> 1,
    'markerStyle'=> 'disc',
    'separator'=> 'none',
    'enableCollapse'=> true,
    'collapseLimit'=> 0,
    'collapseBehavior'=> 'open',
    'activeiconName'=> 'wordpress-chevronUp',
    'inactiveiconName'=> 'wordpress-chevronDown',
    'iconalignment'=> array('Desktop'=>'space-between','Tablet'=>'space-between','Mobile'=>'space-between'),
    'overallalignment'=>'right',
    'titlebg'=>'',
    'titlecolor'=>'black',
    'contentbg'=>'',
    'contentcolor'=>'black',
    'iconsize'=>array( 'Desktop'=>'36px', 'Tablet'=>'36px', 'Mobile'=>'36px'),
    'iconbg'=>'',
    'iconbghvr'=>'',
    'iconcolor'=>'black',
    'iconcolorhvr'=>'',
    'iconactivecolor'=>'',
    'scroll'=>false,
    'scrollheight'=>array('Desktop'=> '300px', 'Tablet'=>'300px', 'Mobile'=>'300px'),
    'hierarchyType'=>'nested',
    'enableShrink'=>false,
)
?>
