<?php
return array(
    // Settings
        'uniqueId' => '',
        'globalwidth' => 0,
        'image' => '',
        'opacity' => 1,
        'overlaytransitiontime' => 0.5,
        'imagetransitiontime' => 0.5,
        'overlay' => true,
        'imagehvreffect' => 'flip',
        'imagehvrfilter' => 'none',
        'imageoverlayouteffect' => 'none',
        'overlaycolor' => 'rgba(106, 111, 248, 0.17)',
        'focalPoint' => array(
            'x' => 0.5,
            'y' => 0.5,
        ),
        'imageborderradiuscircle' => 'square',
        'imagecover' => 'cover',
        'imageaspectratio' => 'original',
        'duotone' => '',
        'showPreview' => false,
        'overlayalignment' => 'center center',
        'overlayalignmenttablet' => 'center center',
        'overlayalignmentmobile' => 'center center',
        'overlayalignmentvertical' => 'center',
        'imagealttext'  => '',
        'dbox' => false,
        'flipside' => 'top',
        'innerBlockUniqueIds'=> [],

        // image Border
            'imageborder' => array(
                'topcolor' => '',
                'topwidth' => '0px',
                'topstyle' => 'solid',
                'bottomcolor' => '',
                'bottomwidth' => '0px',
                'bottomstyle' => 'solid',
                'leftcolor' => '',
                'leftwidth' => '0px',
                'leftstyle' => 'solid',
                'rightcolor' => '',
                'rightwidth' => '0px',
                'rightstyle' => 'solid',
            ),
    
        // image Border Radius
            'imageborderRadius' => array(
                'top' => '4px',
                'bottom' => '4px',
                'left' => '4px',
                'right' => '4px',
            ),

        //back setting 
        'backimage' => '',
        'backopacity' => 1,
        'backoverlaycolor' => 'rgba(106, 111, 248, 0.17)',
        'backfocalPoint' => array(
            'x' => 0.5,
            'y' => 0.5,
        ),
        'backimageborderradiuscircle' => 'square',
        'backimagecover' => 'cover',
        'backimageaspectratio' => 'original',
        'backduotone' => '',
        'backoverlayalignment' => 'center center',
        'backoverlayalignmenttablet' => 'center center',
        'backoverlayalignmentmobile' => 'center center',
        'backoverlayalignmentvertical' => 'center',
        'backimagealttext'  => '',

    //Advanced
    
        'buttonpadding'=> array(),
        'buttonmargin'=> array(),
        'advancedropshadow'=> array(),
        'advanceborder'=>array(),
        'advanceborderradius'=>array(),
        'advancedropshadowhvr'=> array(),
        'advanceborderhvr'=>array(),
	    'advanceborderradiushvr'=>array(),

        'classNamemain' => '',
        'globalwidth'=> '',
        'width' => '',
        'customWidthlayout' => '',
        'widthType' => 'default',
        'customWidthUnit' => '%',
        'customWidth' => 100,
        'customWidthTablet' => 100,
        'customWidthMobile' => 100,
        'customHeightUnit' => 'px',
        'customHeight' => 400,
        'customHeightTablet' => 400,
        'customHeightMobile' => 400,
        'position' => 'relative',
        'horizontalOrientation' => 'left',
        'horizontalOrientationOffsetUnit' => 'px',
        'horizontalOrientationOffsetRightUnit' => 'px',
        'horizontalOrientationOffset' => 0,
        'horizontalOrientationOffsetRight' => 0,
        'verticalOrientation' => 'top',
        'verticalOrientationOffsetTopUnit' => 'px',
        'verticalOrientationOffsetBottomUnit' => 'px',
        'verticalOrientationOffsetTop' => 0,
        'verticalOrientationOffsetBottom' => 0,
        'zIndex' => 0,
        'selfAlign' => 'start',
        'order' => 'start',
        'customOrder' => 0,
        'flexSize' => 'none',
        'flexGrow' => 1,
        'flexShrink' => 1,
        'backgroundType' => 'color',
        'backgroundColor' => 'transparent',
        'backgroundImage' => null,
        'backgroundGradient' => 'linear-gradient(135deg,#0F2027 0%, #203A43 0%, #2c5364 100%)',
        'backgroundPosition' => array('x' => 0.5, 'y' => 0.5),
        'backgroundAttachment' => 'scroll',
        'backgroundRepeat' => 'no-repeat',
        'backgroundSize' => 'cover',
        'backgroundTypeHvr' => 'color',
        'backgroundColorHvr' => '',
        'backgroundImageHvr' => null,
        'backgroundGradientHvr' => 'linear-gradient(135deg,#0F2027 0%, #203A43 0%, #2c5364 100%)',
        'backgroundPositionHvr' => array('x' => 0.5, 'y' => 0.5),
        'backgroundAttachmentHvr' => 'scroll',
        'backgroundRepeatHvr' => 'no-repeat',
        'backgroundSizeHvr' => 'cover',
        'transitionAll' => 0,
        'responsiveTogHideDesktop'=> false,
        'responsiveTogHideTablet'=> false,
        'responsiveTogHideMobile'=> false,
);
?>
