<?php
return array(
    // Settings
        'globalwidth' => 0,
        'image' => '',
        'opacity' => 1,
        'overlaytransitiontime' => 0.5,
        'imagetransitiontime' => 0.5,
        'overlay' => false,
        'imagehvreffect' => 'none',
        'imagehvranimation' => 'none',
        'imagehvrfilter' => 'none',
        'imageoverlayouteffect' => 'none',
        'overlayhvrcolor' => "",
        'overlaycolor' => '',
        'focalPoint' => array(
            'x' => 0.5,
            'y' => 0.5,
        ),
        'imageborderradiuscircle' => 'square',
        'imagecover' => 'cover',
        'aspectRatio' => array(
            'Desktop' => '4/3',
            'Tablet' => '4/3',
            'Mobile' => '4/3',
        ),
        'link' => array(),
        'duotone' => array(),
        'showPreview' => false,
        'overlayalignment' => 'center center',
        'overlayalignmentvertical' => 'center',
        'overlayalignmenttablet' => 'center center',
        'overlayalignmentverticaltablet' => 'center',
        'overlayalignmentmobile' => 'center center',
        'overlayalignmentverticalmobile' => 'center',
        'rotation'=> '0',
        'parentBlockAttributes' => array(),
        'parentBlock'=> "",
        'imageborder'=> array(
            'advanceRadiusglobal'=> array(
                'desktop'=> array(),
                'tablet' => array(),
                'mobile'=> array()
            ),
        ),
        'imageborderRadius'=> array(
            'advanceRadiusglobal'=> array(
                'desktop'=> array(),
                'tablet' => array(),
                'mobile'=> array()
            ),
        ),
        'advBorderglobal'=> array(
            'advanceRadiusglobal'=> array(
                'desktop'=> array(),
                'tablet' => array(),
                'mobile'=> array()
            ),
        ),
        'advanceRadiusglobal'=> array(
            'desktop'=> array(),
            'tablet' => array(),
            'mobile'=> array()
        ),
        'overlayopacity' => 0.5,
        'animationData'=> array(
            'effect'=> array(),
            'imageAnimation'=> array(),
            'mask'=> array(),
            'hovereffect'=> array()
        ),
        'advanceglobaldropshadow'=>array(),
        'imagealignment' =>  array(
            "Desktop" => "",
            "Tablet" => "",
            "Mobile" => ""
        ),
        'contentani' => true,
        'wrapppereffect3color' => 'white',
        'overlayshow'=>false,
        'maskshape'=> 'none',
        'masksize'=>'auto',
        'maskposition'=>'center center',
        'maskrepeat'=>'no-repeat',
        'imagealttext'=>'',
        'captiontext'=> 'Write Caption...',
        'caption'=>false,
        'captionsize'=>16,
        'captionfontweight'=> 'normal',
        'captionsizeTablet'=>16,
        'captionfontweightTablet'=> 'normal',
        'captionsizeMobile'=>16,
        'captionfontweightMobile'=> 'normal',
        'captioncolor'=>'black',
        'captionalignment' =>  array(
            "Desktop" => "",
            "Tablet" => "",
            "Mobile" => ""
        ),
        'imagewidth'=>array(),
        'imageheight'=>array(),
        'overlaybordertype'=>'color',
        'overlaybordergradient'=>'linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%)',
        'overlayborderimage'=>'',
        'overlayborderimagetype'=>'none',
        'overlaygradienttop'=>'5px',
        'overlaygradientbottom'=>'5px',
        'overlaygradientleft'=>'5px',
        'overlaygradientright'=>'5px',
        'overlayimagetop'=>'5px',
        'overlayimagebottom'=>'5px',
        'overlayimageleft'=>'5px',
        'overlayimageright'=>'5px',
        'overlayspace'=>'space',
        'borderimagesize'=> 30,
        'imagebackgroundSize' => 'cover',
        'borderimageoutset' => 5,
        'animationsettings' => 'without-hvr',
        'wrapperanimation'=>'none',
        'overlaywrapper'=> 'none',
        'animationhover' => true,
        'frameshow'=>true,
        'typeimage'=>'image',
        'videoUrl'=>'',
        'videosize'=>300,
        'autoplay'=>true,
        'loop'=>true,
        'controls'=>true,
        'muted'=>true,
        'fallbackImageUrl'=>'',
        'imageboxShadow'=> array(),
        'borderframe' => false,
        'position' => array(
            'width'=> array('Desktop'=>'100%', 'Tablet'=>'100%', 'Mobile'=>'100%'),
            'height'=> array('Desktop'=>'100%', 'Tablet'=>'100%', 'Mobile'=>'100%'),
            'top'=> array('Desktop'=>'0%', 'Tablet'=>'0%', 'Mobile'=>'0%'),
            'left'=> array('Desktop'=>'0%', 'Tablet'=>'0%', 'Mobile'=>'0%'),
        ),
        'editor' => false,
)
?>
