<?php
return array(
    // Settings
        'globalwidth' => 0,
        'image' => '',
        'opacity' => 1,
        'overlaytransitiontime' => 0.5,
        'imagetransitiontime' => 0.5,
        'overlay' => false,
        'imagehvreffect' => 'none',
        'imagehvranimation' => 'none',
        'imagehvrfilter' => 'none',
        'imageoverlayouteffect' => 'none',
        'overlayhvrcolor' => '',
        'overlaycolor' => 'transparent',
        'focalPoint' => array(
            'x' => 0.5,
            'y' => 0.5,
        ),
        'imageborderradiuscircle' => 'square',
        'imagecover' => 'cover',
        'imageaspectratio' => 'original',
        'imageaspectratiotablet' => 'original',
        'imageaspectratiomobile' => 'original',
        'duotone' => '',
        'showPreview' => false,
        'overlayalignment' => 'center center',
        'overlayalignmentvertical' => 'center',
        'overlayalignmenttablet' => 'center center',
        'overlayalignmentverticaltablet' => 'center',
        'overlayalignmentmobile' => 'center center',
        'overlayalignmentverticalmobile' => 'center',
        'rotation'=> '0',
        'parentBlockAttributes' => array(),
        'parentBlock'=> "",

            'imageborder'=> array(
                'advanceRadiusglobal'=> array(
            'desktop'=> array(),
            'tablet' => array(),
            'mobile'=> array()
          ),
            ),
          'imageborderRadius'=> array(
            'advanceRadiusglobal'=> array(
            'desktop'=> array(),
            'tablet' => array(),
            'mobile'=> array()
          ),
          ),

          'advanceborderglobal'=> array(
            'advanceRadiusglobal'=> array(
            'desktop'=> array(),
            'tablet' => array(),
            'mobile'=> array()
          ),
          ),
          'advanceRadiusglobal'=> array(
            'desktop'=> array(),
            'tablet' => array(),
            'mobile'=> array()
          ),
            'advanceglobaldropshadow'=>array(),
            'imagealignment' => 'center',
            'imagealignmenttablet' => 'center',
            'imagealignmentmobile' => 'center',
            'wrapppereffect3color' => 'white',
            'overlayshow'=>false,
            'maskshape'=> 'none',
            'masksize'=>'auto',
            'maskposition'=>'center center',
            'maskrepeat'=>'no-repeat',
            'imagealttext'=>'',
            'captiontext'=> 'Write Caption...',
            'caption'=>false,
            'captionsize'=>16,
            'captionfontweight'=> 'normal',
            'captionsizeTablet'=>16,
            'captionfontweightTablet'=> 'normal',
            'captionsizeMobile'=>16,
            'captionfontweightMobile'=> 'normal',
            'captioncolor'=>'black',
            'captionalignment'=>'center',
            'captionalignmentTablet'=>'center',
            'captionalignmentMobile'=>'center',
            'imagewidth'=>'',
            'imageheight'=>'',
            'imagewidthtablet'=>'',
            'imageheighttablet'=>'',
            'imagewidthmobile'=>'',
            'imageheightmobile'=>'',
            'overlaybordertype'=>'color',
            'overlaybordergradient'=>'linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%)',
            'overlayborderimage'=>'',
            'overlayborderimagetype'=>'none',
            'overlaygradienttop'=>'5px',
            'overlaygradientbottom'=>'5px',
            'overlaygradientleft'=>'5px',
            'overlaygradientright'=>'5px',
            'overlayimagetop'=>'5px',
            'overlayimagebottom'=>'5px',
            'overlayimageleft'=>'5px',
            'overlayimageright'=>'5px',
            'overlayspace'=>'space',
            'borderimagesize'=> 30,
            'imagebackgroundSize' => 'cover',
            'overlaywidth'=>'100%',
            'borderimageoutset' => 5,
            'overlayheight'=>'100%',
            'overlaywidthtablet'=>'100%',
            'overlayheighttablet'=>'100%',
            'overlaywidthmobile'=>'100%',
            'overlayheightmobile'=>'100%',
            'overlayleft'=>'0px',
            'overlaytop'=>'0px',
            'overlaylefttablet'=>'0px',
            'overlaytoptablet'=>'0px',
            'overlayleftmobile'=>'0px',
            'overlaytopmobile'=>'0px',
            'animationsettings' => 'without-hvr',
            'wrapperanimation'=>'none',
            'overlaywrapper'=> 'none',
            'animationhover' => true,
            'frameshow'=>false,
            'overlayOpacity' => 0.5,
            'overlayOpacityhvr' => 0.5,
            'typeimage'=>'image',
            'videoUrl'=>'',
            'videosize'=>300,
            'autoplay'=>true,
            'loop'=>true,
            'controls'=>true,
            'muted'=>true,
            'fallbackImageUrl'=>'',
            'imageboxShadow'=> array(),

        //Advanced
           
            'advancedropshadow'=> array(),
            'advanceborder'=>array(),
            'advanceborderradius'=>array(),
            'advancedropshadowhvr'=> array(),
            'advanceborderhvr'=>array(),
            'advanceborderradiushvr'=>array(),
            'classNamemain' => '',
            'globalwidth'=> '',
            'width' => '',
            'customWidthlayout' => '',
            'widthType' => 'default',
            'customWidthUnit' => '%',
            'customWidth' => 100,
            'customWidthTablet' => 100,
            'customWidthMobile' => 100,
            'position' => 'relative',
            'horizontalOrientation' => 'left',
            'horizontalOrientationOffsetUnit' => 'px',
            'horizontalOrientationOffsetRightUnit' => 'px',
            'horizontalOrientationOffset' => 0,
            'horizontalOrientationOffsetRight' => 0,
            'verticalOrientation' => 'top',
            'verticalOrientationOffsetTopUnit' => 'px',
            'verticalOrientationOffsetBottomUnit' => 'px',
            'verticalOrientationOffsetTop' => 0,
            'verticalOrientationOffsetBottom' => 0,
            'zIndex' => 0,
            'selfAlign' => 'start',
            'order' => 'start',
            'customOrder' => 0,
            'flexSize' => 'none',
            'flexGrow' => 1,
            'flexShrink' => 1,
            'backgroundType' => 'color',
            'backgroundColor' => 'transparent',
            'backgroundImage' => null,
            'backgroundGradient' => 'linear-gradient(135deg,#0F2027 0%, #203A43 0%, #2c5364 100%)',
            'backgroundPosition' => array('x' => 0.5, 'y' => 0.5),
            'backgroundAttachment' => 'scroll',
            'backgroundRepeat' => 'no-repeat',
            'backgroundSize' => 'cover',
            'backgroundTypeHvr' => 'color',
            'backgroundColorHvr' => '',
            'backgroundImageHvr' => null,
            'backgroundGradientHvr' => 'linear-gradient(135deg,#0F2027 0%, #203A43 0%, #2c5364 100%)',
            'backgroundPositionHvr' => array('x' => 0.5, 'y' => 0.5),
            'backgroundAttachmentHvr' => 'scroll',
            'backgroundRepeatHvr' => 'no-repeat',
            'backgroundSizeHvr' => 'cover',
            'transitionAll' => 0,
            'responsiveTogHideDesktop'=> false,
            'responsiveTogHideTablet'=> false,
            'responsiveTogHideMobile'=> false
)
?>
